import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Picture Upload",
  description: "Picture Upload Website generated by GoFunding.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.png" />
        <title>Picture Upload</title>
      </head>
      <body className={`${inter.className} min-h-screen`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
